export const genresAnime = [
    { id: 1, name: "Action" },
    { id: 2, name: "Adventure" },
    { id: 3, name: "Avant Garde" },
    { id: 4, name: "Award Winning" },
    { id: 5, name: "Boys Love" },
    { id: 6, name: "Comedy" },
    { id: 7, name: "Drama" },
    { id: 8, name: "Fantasy" },
    { id: 9, name: "Girls Love" },
    { id: 10, name: "Gourmet" },
    { id: 11, name: "Horror" },
    { id: 12, name: "Mystery" },
    { id: 13, name: "Romance" },
    { id: 14, name: "Sci-Fi" },
    { id: 15, name: "Slice of Life" },
    { id: 16, name: "Sports" },
    { id: 17, name: "Supernatural" },
    { id: 18, name: "Suspense" },
    { id: 19, name: "Ecchi" },
    { id: 20, name: "Erotica" },
    { id: 21, name: "Hentai" },
    { id: 22, name: "Adult Cast" },
    { id: 23, name: "Anthropomorphic" },
    { id: 24, name: "CGDCT" },
    { id: 25, name: "Childcare" },
    { id: 26, name: "Combat Sports" },
    { id: 27, name: "Crossdressing" },
    { id: 28, name: "Delinquents" },
    { id: 29, name: "Detective" },
    { id: 30, name: "Educational" },
    { id: 31, name: "Gag Humor" },
    { id: 32, name: "Gore" },
    { id: 33, name: "Harem" },
    { id: 34, name: "High Stakes Game" },
    { id: 35, name: "Historical" },
    { id: 36, name: "Idols (Female)" },
    { id: 37, name: "Idols (Male)" },
    { id: 38, name: "Isekai" },
    { id: 39, name: "Iyashikei" },
    { id: 40, name: "Love Polygon" },
    { id: 41, name: "Magical Sex Shift" },
    { id: 42, name: "Mahou Shoujo" },
    { id: 43, name: "Martial Arts" },
    { id: 44, name: "Mecha" },
    { id: 45, name: "Medical" },
    { id: 46, name: "Military" },
    { id: 47, name: "Music" },
    { id: 48, name: "Mythology" },
    { id: 49, name: "Organized Crime" },
    { id: 50, name: "Otaku Culture" },
    { id: 51, name: "Parody" },
    { id: 52, name: "Performing Arts" },
    { id: 53, name: "Pets" },
    { id: 54, name: "Psychological" },
    { id: 55, name: "Racing" },
    { id: 56, name: "Reincarnation" },
    { id: 57, name: "Reverse Harem" },
    { id: 58, name: "Romantic Subtext" },
    { id: 59, name: "Samurai" },
    { id: 60, name: "School" },
    { id: 61, name: "Showbiz" },
    { id: 62, name: "Space" },
    { id: 63, name: "Strategy Game" },
    { id: 64, name: "Super Power" },
    { id: 65, name: "Survival" },
    { id: 66, name: "Team Sports" },
    { id: 67, name: "Time Travel" },
    { id: 68, name: "Vampire" },
    { id: 69, name: "Video Game" },
    { id: 70, name: "Visual Arts" },
    { id: 71, name: "Workplace" },
    { id: 72, name: "Josei" },
    { id: 73, name: "Kids" },
    { id: 74, name: "Seinen" },
    { id: 75, name: "Shoujo" },
    { id: 76, name: "Shounen" }
  ];